# Complete reducer subgraph

import os
import re
from pathlib import Path

from google import genai
from google.genai import types
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, START, StateGraph

from backend.llm import llm
from backend.schemas import GlobalImagePlan
from backend.state import State


# ============================================================
# Merge Content
# ============================================================

def merge_content(state: State) -> dict:
    plan = state["plan"]

    if plan is None:
        raise ValueError("merge_content called without plan.")

    ordered_sections = [
        md
        for _, md in sorted(
            state["sections"],
            key=lambda x: x[0],
        )
    ]

    body = "\n\n".join(ordered_sections).strip()

    merged_md = f"# {plan.blog_title}\n\n{body}\n"

    return {
        "merged_md": merged_md
    }


# ============================================================
# Image Planning Prompt
# ============================================================

DECIDE_IMAGES_SYSTEM = """You are an expert technical editor.

Decide if images/diagrams are needed for THIS blog.

Rules:
- Max 3 images total.
- Each image must materially improve understanding (diagram/flow/table-like visual).
- Insert placeholders exactly:
    [[IMAGE_1]]
    [[IMAGE_2]]
    [[IMAGE_3]]
- If no images needed:
    md_with_placeholders must equal input
    images=[]
- Avoid decorative images.
- Prefer technical diagrams with short labels.

Return strictly GlobalImagePlan.
"""


# ============================================================
# Decide Images
# ============================================================

def decide_images(state: State) -> dict:

    planner = llm.with_structured_output(GlobalImagePlan)

    merged_md = state["merged_md"]
    plan = state["plan"]

    assert plan is not None

    image_plan = planner.invoke(
        [
            SystemMessage(content=DECIDE_IMAGES_SYSTEM),
            HumanMessage(
                content=(
                    f"Blog kind: {plan.blog_kind}\n"
                    f"Topic: {state['topic']}\n\n"
                    "Insert placeholders + propose image prompts.\n\n"
                    f"{merged_md}"
                )
            ),
        ]
    )

    return {
        "md_with_placeholders": image_plan.md_with_placeholders,
        "image_specs": [
            img.model_dump()
            for img in image_plan.images
        ],
    }
    
# ============================================================
# Gemini Image Generation
# ============================================================

def _gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires:
        pip install google-genai

    Environment Variable:
        GOOGLE_API_KEY
    """

    api_key = os.environ.get("GOOGLE_API_KEY")

    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    client = genai.Client(api_key=api_key)

    response = client.models.generate_content(
        model="gemini-2.5-flash-image",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_ONLY_HIGH",
                )
            ],
        ),
    )

    parts = getattr(response, "parts", None)

    if not parts and getattr(response, "candidates", None):
        try:
            parts = response.candidates[0].content.parts
        except Exception:
            parts = None

    if not parts:
        raise RuntimeError(
            "No image content returned (quota/safety/SDK change)."
        )

    for part in parts:
        inline = getattr(part, "inline_data", None)

        if inline and getattr(inline, "data", None):
            return inline.data

    raise RuntimeError("No inline image bytes found.")


# ============================================================
# Helpers
# ============================================================

def _safe_slug(title: str) -> str:
    slug = title.strip().lower()

    slug = re.sub(r"[^a-z0-9 _-]+", "", slug)
    slug = re.sub(r"\s+", "_", slug).strip("_")

    return slug or "blog"


# ============================================================
# Generate Images + Replace Placeholders
# ============================================================

def generate_and_place_images(state: State) -> dict:

    plan = state["plan"]

    assert plan is not None

    markdown = (
        state.get("md_with_placeholders")
        or state["merged_md"]
    )

    image_specs = state.get("image_specs", []) or []

    # No images required
    if not image_specs:

        filename = f"{_safe_slug(plan.blog_title)}.md"

        Path(filename).write_text(
            markdown,
            encoding="utf-8",
        )

        return {
            "final": markdown
        }

    images_dir = Path("images")
    images_dir.mkdir(exist_ok=True)

    for spec in image_specs:

        placeholder = spec["placeholder"]
        filename = spec["filename"]

        output_path = images_dir / filename

        # Generate only if image doesn't exist
        if not output_path.exists():

            try:
                image_bytes = _gemini_generate_image_bytes(
                    spec["prompt"]
                )

                output_path.write_bytes(image_bytes)

            except Exception as e:

                error_block = (
                    f"> **[IMAGE GENERATION FAILED]** "
                    f"{spec.get('caption','')}\n>\n"
                    f"> **Alt:** {spec.get('alt','')}\n>\n"
                    f"> **Prompt:** {spec.get('prompt','')}\n>\n"
                    f"> **Error:** {e}\n"
                )

                markdown = markdown.replace(
                    placeholder,
                    error_block,
                )

                continue

        image_markdown = (
            f"![{spec['alt']}](images/{filename})\n"
            f"*{spec['caption']}*"
        )

        markdown = markdown.replace(
            placeholder,
            image_markdown,
        )

    filename = f"{_safe_slug(plan.blog_title)}.md"

    Path(filename).write_text(
        markdown,
        encoding="utf-8",
    )

    return {
        "final": markdown
    }


# ============================================================
# Reducer Subgraph
# ============================================================

reducer_graph = StateGraph(State)

reducer_graph.add_node(
    "merge_content",
    merge_content,
)

reducer_graph.add_node(
    "decide_images",
    decide_images,
)

reducer_graph.add_node(
    "generate_and_place_images",
    generate_and_place_images,
)

reducer_graph.add_edge(
    START,
    "merge_content",
)

reducer_graph.add_edge(
    "merge_content",
    "decide_images",
)

reducer_graph.add_edge(
    "decide_images",
    "generate_and_place_images",
)

reducer_graph.add_edge(
    "generate_and_place_images",
    END,
)

reducer_subgraph = reducer_graph.compile()